const projects = [
  {
    id: 1,
    image: "/images/expense.png",
    name: "Expense Tracker App",
    git: "https://github.com/hassan-dev51/expense_tracker_app",
    url: "https://budget-saving-application.netlify.app/",
    desc: "For daily usage to keep remember daily transaction",
    tag: "React App",
  },
  {
    id: 2,
    image: "/images/covid.png",
    name: "Covid Tracker App",
    git: "https://github.com/hassan-dev51/corona_tracker_app",
    url: "https://covid-ninetee-app.netlify.app/",
    desc: "Known the current corona virus cases all over the world",
    tag: "React App",
  },
  {
    id: 3,
    image: "/images/todo.png",
    name: "Todo App",
    git: "https://github.com/hassan-dev51/todo_app",
    url: "https://todo-list-crud-app.netlify.app/",
    desc: "Add Items to keep Remember, while on shopping",
    tag: "React App",
  },
  {
    id: 4,
    image: "/images/panaverse.png",
    name: "Panaverse Website",
    git: "https://github.com/hassan-dev51/Assignment01_Nextjs_TodoApp/tree/main/panaverse",
    url: "https://panaverse-lite.vercel.app/",
    desc: "Panaverse Dao website about detailed documentation",
    tag: "Next JS",
  },
  {
    id: 5,
    image: "/images/piaic.png",
    name: "PIAIC Website",
    git: "https://github.com/hassan-dev51/piaic",
    url: "https://piaic-lite.vercel.app/",
    desc: "PIAIC Landing page with framer motion library",
    tag: "Next JS",
  },
  {
    id: 6,
    image: "/images/pricing.png",
    name: "Figma Design",
    git: "https://github.com/hassan-dev51/Assignment01_Nextjs_TodoApp/tree/main/pricing",
    url: "https://pricing-ui-assignment.vercel.app/",
    desc: "A Figma Project using Next JS with Chakra UI  ",
    tag: "Next JS",
  },
  {
    id: 7,
    image: "/images/intern.png",
    name: "PSD Design",
    git: "https://github.com/hassan-dev51/internship",
    url: "https://internshiptesting.netlify.app/",
    desc: "A Photoshop design project for a BRAND",
    tag: "HTML",
  },
];
export default projects;
