const projects = [
  {
    id: 1,
    image: "/images/expense.png",
    name: "Expense Tracker App",
    git: "https://github.com/hassan-dev51/Q2-Projects/tree/main/expense_app",
    url: "https://expense-lite.vercel.app/",
    desc: "For daily usage to keep remember daily transaction",
    tag: "Next JS App",
  },
  {
    id: 2,
    image: "/images/covid.png",
    name: "Covid Tracker App",
    git: "https://github.com/hassan-dev51/covid-19",
    url: "https://covid-19-lite.vercel.app/",
    desc: "Known the current corona virus cases all over the world",
    tag: "React App",
  },
  {
    id: 3,
    image: "/images/todo.png",
    name: "Todo App",
    git: "https://github.com/hassan-dev51/todo_app",
    url: "https://todo-list-crud-app.netlify.app/",
    desc: "Add Items to keep Remember, while on shopping",
    tag: "React App",
  },
  {
    id: 4,
    image: "/images/panaverse.png",
    name: "Panaverse Website",
    git: "https://github.com/hassan-dev51/Assignment01_Nextjs_TodoApp/tree/main/panaverse",
    url: "https://panaverse-lite.vercel.app/",
    desc: "Panaverse Dao website about detailed documentation",
    tag: "Next JS",
  },
  {
    id: 5,
    image: "/images/piaic.png",
    name: "PIAIC Website",
    git: "https://github.com/hassan-dev51/piaic",
    url: "https://piaic-lite.vercel.app/",
    desc: "PIAIC Landing page with framer motion library",
    tag: "Next JS",
  },
  {
    id: 6,
    image: "/images/pricing.png",
    name: "Figma Design",
    git: "https://github.com/hassan-dev51/Assignment01_Nextjs_TodoApp/tree/main/pricing",
    url: "https://pricing-ui-assignment.vercel.app/",
    desc: "A Figma Project using Next JS with Chakra UI  ",
    tag: "Next JS",
  },
  {
    id: 7,
    image: "/images/intern.png",
    name: "PSD Design",
    git: "https://github.com/hassan-dev51/internship",
    url: "https://internshiptesting.netlify.app/",
    desc: "A Photoshop design project for a BRAND",
    tag: "HTML",
  },
  {
    id: 7,
    image: "/images/sumrix.png",
    name: "Sumz Article",
    git: "https://github.com/hassan-dev51/ai_summerize_website",
    url: "https://ai-summerize.vercel.app/",
    desc: "Summerize Articles With OpenAI GPT-4",
    tag: "NEXT JS",
  },
  {
    id: 8,
    image: "/images/hackathon.png",
    name: "Dine Market",
    git: "https://github.com/hassan-dev51/hackathon",
    url: "https://hackathon-iota.vercel.app/",
    desc: "E-Commerce site for a brand including payment functionality",
    tag: "NEXT JS",
  },
  {
    id: 9,
    image: "/images/carhub.png",
    name: "Car Rental",
    git: "https://github.com/hassan-dev51/carhub",
    url: "https://carhub-lake.vercel.app/",
    desc: "A car rental website where rent a car according to our need and budget",
    tag: "NEXT JS",
  },
  {
    id: 10,
    image: "/images/shoestore.png",
    name: "Shoe Store Website",
    git: "https://github.com/hassan-dev51/shoes-store",
    url: "https://shoes-store-lite.vercel.app/",
    desc: "Fetching the product from api and displaying on the page",
    tag: "NEXT JS",
  },
  {
    id: 11,
    image: "/images/prompt.png",
    name: "Socail Posting App",
    git: "https://github.com/hassan-dev51/prompt",
    url: "https://prompt-red.vercel.app/",
    desc: "A Full Stack Application where people can share their Posts",
    tag: "NEXT JS",
  },
];
export default projects;
